#! /bin/bash

job_type=$1
Njobs=$2
session_type=$3

session_name=`pwd`

echo "job type is [$job_type]"
echo "number of jobs is [$Njobs]"
echo "session name is [$session_name]"

if [ $Njobs == 'all' ]; then
    Njobs=`lscpu | grep 'CPU(s):' | head -1 | awk '{print $2}'`
    echo "starting jobs based on CPU count : " $Njobs
fi

if [ -z $session_type ] ; then
    session_type='tmux'
    /usr/bin/which tmux || session_type='bg'
fi

if [ $session_type == "bg" ] ; then
    first_job=1
    last_job=$Njobs
fi

if [ $session_type == "tmux" ]; then
    $(tmux list-sessions | grep -q $session_name) || $(tmux new-session -s $session_name -d)
    last_window=$(tmux list-windows -t $session_name | awk ' END {print $1}' | sed s/://)
    first_job=$(( last_window+1 ))
    last_job=$(( $first_job+$Njobs ))
else
    first_job=0
    last_job=$Njobs
fi

echo "_--------"
echo "RUNNING:"

echo "$job_type $session_type $first_job $last_job"

if [ $job_type == "-s" ] ; then
    for i in `seq $first_job $last_job`; do
        sleep .1

        if [ $session_type == "tmux" ]; then
            echo "       starting shell client:"$session_name:$i"  in tmux"
            tmux new-window  -t $session_name:$i 'pworker.py'
        else
            echo "       starting shell client:"$i" in background"
            nohup pworker.py &
        fi
    done
fi

if [ $job_type == "-m" ] ; then
    for i in `seq 1 $Njobs`; do
        sleep 0.1
        echo "starting matlab client:"$i
        if [ $session_type == "tmux" ]; then
            echo "   in tmux"
            tmux new-window -t $session_name '\matlab -singleCompThread -nodesktop -nosplash -r "dbstop if error; pworker; exit"'
        else
            nohup bash -c '\matlab -singleCompThread -nodesktop -nosplash -r "dbstop if error; pworker; exit" &'
        fi
    done
fi
